name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Haskell
        uses: actions/setup-haskell@v1
        with:
          ghc-version: '9.4.8'
          cabal-version: '3.10.2.1'
          stack-version: '2.13.1'

      - name: Build with Stack
        run: stack build --ghc-options="-static -optl-static -optl-pthread"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: atool
          path: $(stack path --local-bin)/atool
